import { GDS_SERVER_CONFIG, GDS_SERVER_CONNECT_MULTIPARTY, GDS_SERVER_HTTPS_LISTENER, GDS_SERVER_HTTP_LISTENER, GDS_SERVER_HTTP_PROXY_LISTENER } from './Chain.info';

import { ExpressApp } from './Config';

module.exports = { ServerChains: { GDS_SERVER_CONFIG, GDS_SERVER_CONNECT_MULTIPARTY, GDS_SERVER_HTTP_LISTENER, GDS_SERVER_HTTPS_LISTENER, GDS_SERVER_HTTP_PROXY_LISTENER }, ExpressApp };