import { CONVERT_TO_SERVER_ADDRESSES, DOCKER_CONFIG, DOCKER_CONNECT, DOCKER_CREATE_API_CHAINS } from './Chain.info';

import Config from './Config';

module.exports = { DockerChains: { DOCKER_CONFIG, DOCKER_CONNECT, DOCKER_CREATE_API_CHAINS, CONVERT_TO_SERVER_ADDRESSES } };